name: schedule

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@master
        with:
          go-version: 1.15
        id: go

      - name: Complete App
        run: |
          git config --local user.email "saber4233@gmail.com"
          git config --local user.name "chongli"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          go run app.go
          git add .
          git commit -m "update by github action"
          git push
